export const COLLECTION_ACTION_TYPES = {
  SET_COLLECTIONS: "collection/SET_COLLECTIONS",
  FETCH_COLLECTIONS_START: "collection/FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "collection/FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAIL: "collection/FETCH_COLLECTIONS_FAIL",
};
